// Create a new GitHub repo under the Karacterhub GitHub App installation
// and push the generated files as the initial commit using the Git Data API.
import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors';
import { createClient } from 'npm:@supabase/supabase-js@2';
import { SignJWT, importPKCS8 } from 'npm:jose@5';

const APP_ID = Deno.env.get('KARACTERHUB_GITHUB_APP_ID');
const APP_PRIVATE_KEY = Deno.env.get('KARACTERHUB_GITHUB_APP_PRIVATE_KEY');
const INSTALLATION_ID = Deno.env.get('KARACTERHUB_GITHUB_APP_INSTALLATION_ID');

async function mintAppJwt(): Promise<string> {
  if (!APP_ID || !APP_PRIVATE_KEY) throw new Error('GitHub App credentials missing');
  // Support both literal newlines and \n-escaped private keys
  const pem = APP_PRIVATE_KEY.includes('\\n') ? APP_PRIVATE_KEY.replace(/\\n/g, '\n') : APP_PRIVATE_KEY;
  const key = await importPKCS8(pem, 'RS256');
  const now = Math.floor(Date.now() / 1000);
  return await new SignJWT({})
    .setProtectedHeader({ alg: 'RS256' })
    .setIssuedAt(now - 60)
    .setExpirationTime(now + 9 * 60)
    .setIssuer(APP_ID)
    .sign(key);
}

async function getInstallationToken(): Promise<string> {
  if (!INSTALLATION_ID) throw new Error('KARACTERHUB_GITHUB_APP_INSTALLATION_ID missing');
  const jwt = await mintAppJwt();
  const r = await fetch(`https://api.github.com/app/installations/${INSTALLATION_ID}/access_tokens`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${jwt}`,
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
  });
  if (!r.ok) throw new Error(`Installation token: ${r.status} ${await r.text()}`);
  const j = await r.json();
  return j.token as string;
}

async function getInstallationOwner(token: string): Promise<{ login: string; type: 'User' | 'Organization' }> {
  const r = await fetch(`https://api.github.com/app/installations/${INSTALLATION_ID}`, {
    headers: { 'Authorization': `Bearer ${await mintAppJwt()}`, 'Accept': 'application/vnd.github+json' },
  });
  if (!r.ok) throw new Error(`Installation lookup: ${r.status}`);
  const j = await r.json();
  return { login: j.account.login, type: j.account.type };
}

function ghHeaders(token: string) {
  return {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
    'User-Agent': 'karadev-agent',
  };
}

async function createRepo(token: string, owner: { login: string; type: string }, name: string, description: string) {
  const url = owner.type === 'Organization'
    ? `https://api.github.com/orgs/${owner.login}/repos`
    : `https://api.github.com/user/repos`;
  const r = await fetch(url, {
    method: 'POST',
    headers: ghHeaders(token),
    body: JSON.stringify({ name, description, private: false, auto_init: true }),
  });
  if (!r.ok) throw new Error(`Create repo: ${r.status} ${await r.text()}`);
  return await r.json();
}

async function pushFiles(token: string, owner: string, repo: string, branch: string, files: { path: string; content: string }[]) {
  // Get latest commit SHA on default branch
  const refRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${branch}`, { headers: ghHeaders(token) });
  if (!refRes.ok) throw new Error(`Get ref: ${refRes.status} ${await refRes.text()}`);
  const ref = await refRes.json();
  const baseSha = ref.object.sha;

  const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits/${baseSha}`, { headers: ghHeaders(token) });
  const baseCommit = await commitRes.json();
  const baseTreeSha = baseCommit.tree.sha;

  // Create blobs
  const blobs: { path: string; sha: string }[] = [];
  for (const f of files) {
    const b = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/blobs`, {
      method: 'POST',
      headers: ghHeaders(token),
      body: JSON.stringify({ content: btoa(unescape(encodeURIComponent(f.content))), encoding: 'base64' }),
    });
    if (!b.ok) throw new Error(`Blob ${f.path}: ${b.status} ${await b.text()}`);
    const bj = await b.json();
    blobs.push({ path: f.path, sha: bj.sha });
  }

  // Create tree
  const tree = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees`, {
    method: 'POST',
    headers: ghHeaders(token),
    body: JSON.stringify({
      base_tree: baseTreeSha,
      tree: blobs.map(b => ({ path: b.path, mode: '100644', type: 'blob', sha: b.sha })),
    }),
  });
  if (!tree.ok) throw new Error(`Tree: ${tree.status} ${await tree.text()}`);
  const treeJson = await tree.json();

  // Commit
  const commit = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits`, {
    method: 'POST',
    headers: ghHeaders(token),
    body: JSON.stringify({
      message: 'feat: initial scaffold generated by Karadev agent',
      tree: treeJson.sha,
      parents: [baseSha],
    }),
  });
  const commitJson = await commit.json();

  // Update ref
  const update = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`, {
    method: 'PATCH',
    headers: ghHeaders(token),
    body: JSON.stringify({ sha: commitJson.sha, force: false }),
  });
  if (!update.ok) throw new Error(`Update ref: ${update.status} ${await update.text()}`);
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });
  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } } }
    );
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return new Response(JSON.stringify({ error: 'unauthorized' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    const { data: isAdmin } = await supabase.rpc('has_role', { _user_id: user.id, _role: 'admin' });
    if (!isAdmin) return new Response(JSON.stringify({ error: 'forbidden' }), { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });

    const { project_name, description, files } = await req.json();
    if (!project_name || !Array.isArray(files) || !files.length) throw new Error('project_name and files required');

    const token = await getInstallationToken();
    const owner = await getInstallationOwner(token);
    const safeName = `${project_name}-${Date.now().toString(36)}`.replace(/[^a-zA-Z0-9-_]/g, '-').slice(0, 80);
    const repo = await createRepo(token, owner, safeName, description ?? 'Generated by Karadev admin agent');
    await pushFiles(token, owner.login, safeName, repo.default_branch || 'main', files);

    return new Response(JSON.stringify({
      repo_url: repo.html_url,
      repo_name: `${owner.login}/${safeName}`,
      files_count: files.length,
    }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
  } catch (e) {
    return new Response(JSON.stringify({ error: String((e as Error).message ?? e) }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
  }
});